# Day 16 - Preset Financial Screeners

## Objectives

- Load validated financial ratio data
- Build predefined financial screening strategies
- Implement Quality Screener
- Implement Low Debt Screener
- Implement High ROE Screener
- Implement Income Screener
- Implement Balanced Screener
- Generate preset screener reports

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv(
    "../reports/financial_ratios_day12.csv"
)

print("Financial Ratio Data Loaded Successfully")
print("Shape:", df.shape)

df.head()

Financial Ratio Data Loaded Successfully
Shape: (1184, 7)

,company_id,year,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,dividend_payout_ratio
0,ABB,Dec 2012,22.411128,0.0,NaN,1.822492,17.241379
1,ABB,Mar 2014,25.126904,0.0,NaN,1.998244,12.626263
2,ABB,Mar 2014,25.126904,0.0,NaN,1.998244,12.626263
3,ABB,Mar 2015,24.439701,0.0,NaN,1.665939,12.663755
4,ABB,Mar 2015,24.439701,0.0,NaN,1.665939,12.663755

In [3]:
numeric_cols = [
    "return_on_equity_pct",
    "debt_to_equity",
    "interest_coverage",
    "asset_turnover",
    "dividend_payout_ratio"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

print(df[numeric_cols].dtypes)

return_on_equity_pct     float64
debt_to_equity           float64
interest_coverage        float64
asset_turnover           float64
dividend_payout_ratio    float64
dtype: object

In [4]:
latest_df = (
    df.sort_values("year")
      .drop_duplicates(
          subset=["company_id"],
          keep="last"
      )
      .reset_index(drop=True)
)

print("Original Records:", len(df))
print("Latest Company Records:", len(latest_df))

latest_df.head()

Original Records: 1184
Latest Company Records: 92

,company_id,year,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,dividend_payout_ratio
0,ABB,Mar 2024,32.468235,0.022438,121.083333,1.126324,6.078268
1,ADANIENSOL,Mar 2024,9.461277,2.932521,2.063968,0.283696,0.000000
2,ADANIENT,Mar 2024,8.534650,1.671358,2.497695,0.600432,0.149925
3,ADANIGREEN,Mar 2024,12.812691,6.595282,1.461846,0.104670,0.000000
4,ADANIPORTS,Mar 2024,15.354883,0.937322,5.703988,0.228301,0.197433

In [5]:
latest_df = df.copy()

latest_df["year_number"] = pd.to_numeric(
    latest_df["year"].astype(str).str.extract(r"(\d{4})")[0],
    errors="coerce"
)

latest_df = (
    latest_df.sort_values("year_number")
    .drop_duplicates(
        subset=["company_id"],
        keep="last"
    )
    .reset_index(drop=True)
)

print("Original Records:", len(df))
print("Latest Company Records:", len(latest_df))

latest_df[[
    "company_id",
    "year",
    "year_number"
]].head()

Original Records: 1184
Latest Company Records: 92

  company_id      year  year_number
0    HCLTECH  Mar 2024         2024
1       BHEL  Mar 2024         2024
2    HAVELLS  Mar 2024         2024
3        PFC  Mar 2024         2024
4   HDFCLIFE  Mar 2024         2024

In [6]:
quality_screener = latest_df[
    (latest_df["return_on_equity_pct"] >= 15) &
    (latest_df["debt_to_equity"] <= 1) &
    (latest_df["interest_coverage"] >= 3)
].copy()

print(
    "Quality Screener Results:",
    len(quality_screener)
)

quality_screener.head(10)

Quality Screener Results: 37

,company_id,year,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,dividend_payout_ratio,year_number
0,HCLTECH,Mar 2024,23.013931,0.084350,43.757685,1.110165,0.572884,2024
2,HAVELLS,Mar 2024,17.067275,0.040688,22.392857,1.495214,3.461841,2024
6,BOSCHLTD,Mar 2024,20.639920,0.003233,41.078431,0.963814,1.767068,2024
8,BPCL,Mar 2024,35.511337,0.721875,10.624729,2.213652,0.122864,2024
9,LTIM,Mar 2024,22.904386,0.103457,28.770270,1.289464,0.916031,2024
15,TORNTPHARM,Mar 2024,24.154026,0.586639,9.514124,0.739607,3.442029,2024
16,HINDUNILVR,Mar 2024,20.074974,0.028974,57.817625,0.788595,0.933670,2024
25,INFY,Mar 2024,29.788007,0.094864,77.500000,1.129760,NaN,2024
26,BRITANNIA,Mar 2024,54.148693,0.523979,19.310976,1.848435,3.889410,2024
28,SUNPHARMA,Mar 2024,15.094162,0.051424,54.697479,0.568493,0.353798,2024

In [7]:
low_debt_screener = latest_df[
    latest_df["debt_to_equity"] <= 0.5
].copy()

print(
    "Low Debt Screener Results:",
    len(low_debt_screener)
)

low_debt_screener.head(10)

Low Debt Screener Results: 48

,company_id,year,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,dividend_payout_ratio,year_number
0,HCLTECH,Mar 2024,23.013931,0.084350,43.757685,1.110165,0.572884,2024
1,BHEL,Mar 2024,1.153941,0.362386,0.858696,0.399629,10.992908,2024
2,HAVELLS,Mar 2024,17.067275,0.040688,22.392857,1.495214,3.461841,2024
4,HDFCLIFE,Mar 2024,10.732306,0.064776,192.287619,0.335270,1.715375,2024
6,BOSCHLTD,Mar 2024,20.639920,0.003233,41.078431,0.963814,1.767068,2024
9,LTIM,Mar 2024,22.904386,0.103457,28.770270,1.289464,0.916031,2024
13,ULTRACEMCO,Mar 2024,11.629143,0.189331,13.397727,0.703473,0.414049,2024
16,HINDUNILVR,Mar 2024,20.074974,0.028974,57.817625,0.788595,0.933670,2024
20,SHREECEM,Mar 2024,8.370768,0.079988,17.511628,0.734861,0.923254,2024
25,INFY,Mar 2024,29.788007,0.094864,77.500000,1.129760,NaN,2024

In [8]:
high_roe_screener = latest_df[
    latest_df["return_on_equity_pct"] >= 20
].copy()

print(
    "High ROE Screener Results:",
    len(high_roe_screener)
)

high_roe_screener.head(10)

High ROE Screener Results: 34

,company_id,year,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,dividend_payout_ratio,year_number
0,HCLTECH,Mar 2024,23.013931,0.084350,43.757685,1.110165,0.572884,2024
3,PFC,Mar 2024,26.160934,8.521864,0.579224,0.088084,0.086920,2024
6,BOSCHLTD,Mar 2024,20.639920,0.003233,41.078431,0.963814,1.767068,2024
8,BPCL,Mar 2024,35.511337,0.721875,10.624729,2.213652,0.122864,2024
9,LTIM,Mar 2024,22.904386,0.103457,28.770270,1.289464,0.916031,2024
15,TORNTPHARM,Mar 2024,24.154026,0.586639,9.514124,0.739607,3.442029,2024
16,HINDUNILVR,Mar 2024,20.074974,0.028974,57.817625,0.788595,0.933670,2024
17,TVSMOTOR,Mar 2024,26.223467,3.833432,2.852697,0.931492,1.292861,2024
22,RECLTD,Mar 2024,20.396539,6.424917,1.598871,0.086680,0.212089,2024
25,INFY,Mar 2024,29.788007,0.094864,77.500000,1.129760,NaN,2024

In [9]:
income_screener = latest_df[
    (latest_df["dividend_payout_ratio"] >= 20) &
    (latest_df["return_on_equity_pct"] >= 10)
].copy()

print(
    "Income Screener Results:",
    len(income_screener)
)

income_screener.head(10)

Income Screener Results: 0

Empty DataFrame
Columns: [company_id, year, return_on_equity_pct, debt_to_equity, interest_coverage, asset_turnover, dividend_payout_ratio, year_number]
Index: []

In [10]:
balanced_screener = latest_df[
    (latest_df["return_on_equity_pct"] >= 12) &
    (latest_df["debt_to_equity"] <= 1.5) &
    (latest_df["asset_turnover"] >= 0.5)
].copy()

print(
    "Balanced Screener Results:",
    len(balanced_screener)
)

balanced_screener.head(10)

Balanced Screener Results: 39

,company_id,year,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,dividend_payout_ratio,year_number
0,HCLTECH,Mar 2024,23.013931,0.084350,43.757685,1.110165,0.572884,2024
2,HAVELLS,Mar 2024,17.067275,0.040688,22.392857,1.495214,3.461841,2024
6,BOSCHLTD,Mar 2024,20.639920,0.003233,41.078431,0.963814,1.767068,2024
8,BPCL,Mar 2024,35.511337,0.721875,10.624729,2.213652,0.122864,2024
9,LTIM,Mar 2024,22.904386,0.103457,28.770270,1.289464,0.916031,2024
15,TORNTPHARM,Mar 2024,24.154026,0.586639,9.514124,0.739607,3.442029,2024
16,HINDUNILVR,Mar 2024,20.074974,0.028974,57.817625,0.788595,0.933670,2024
25,INFY,Mar 2024,29.788007,0.094864,77.500000,1.129760,NaN,2024
26,BRITANNIA,Mar 2024,54.148693,0.523979,19.310976,1.848435,3.889410,2024
28,SUNPHARMA,Mar 2024,15.094162,0.051424,54.697479,0.568493,0.353798,2024

In [11]:
preset_summary = pd.DataFrame({
    "preset_name": [
        "Quality Screener",
        "Low Debt Screener",
        "High ROE Screener",
        "Income Screener",
        "Balanced Screener"
    ],
    "records_found": [
        len(quality_screener),
        len(low_debt_screener),
        len(high_roe_screener),
        len(income_screener),
        len(balanced_screener)
    ]
})

preset_summary

         preset_name  records_found
0   Quality Screener             37
1  Low Debt Screener             48
2  High ROE Screener             34
3    Income Screener              0
4  Balanced Screener             39

In [12]:
quality_screener["preset"] = "Quality"
low_debt_screener["preset"] = "Low Debt"
high_roe_screener["preset"] = "High ROE"
income_screener["preset"] = "Income"
balanced_screener["preset"] = "Balanced"

In [13]:
all_preset_results = pd.concat(
    [
        quality_screener,
        low_debt_screener,
        high_roe_screener,
        income_screener,
        balanced_screener
    ],
    ignore_index=True
)

print(
    "Total Preset Result Records:",
    len(all_preset_results)
)

all_preset_results.head()

Total Preset Result Records: 158

,company_id,year,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,dividend_payout_ratio,year_number,preset
0,HCLTECH,Mar 2024,23.013931,0.084350,43.757685,1.110165,0.572884,2024,Quality
1,HAVELLS,Mar 2024,17.067275,0.040688,22.392857,1.495214,3.461841,2024,Quality
2,BOSCHLTD,Mar 2024,20.639920,0.003233,41.078431,0.963814,1.767068,2024,Quality
3,BPCL,Mar 2024,35.511337,0.721875,10.624729,2.213652,0.122864,2024,Quality
4,LTIM,Mar 2024,22.904386,0.103457,28.770270,1.289464,0.916031,2024,Quality

In [14]:
quality_screener.to_csv(
    "../reports/day16_quality_screener.csv",
    index=False
)

low_debt_screener.to_csv(
    "../reports/day16_low_debt_screener.csv",
    index=False
)

high_roe_screener.to_csv(
    "../reports/day16_high_roe_screener.csv",
    index=False
)

income_screener.to_csv(
    "../reports/day16_income_screener.csv",
    index=False
)

balanced_screener.to_csv(
    "../reports/day16_balanced_screener.csv",
    index=False
)

preset_summary.to_csv(
    "../reports/day16_preset_summary.csv",
    index=False
)

all_preset_results.to_csv(
    "../reports/day16_all_preset_results.csv",
    index=False
)

print("Day 16 Preset Screener Reports Saved Successfully!")

Day 16 Preset Screener Reports Saved Successfully!

# Day 16 Summary

## Preset Screeners Completed

- Loaded validated financial ratio data.
- Selected the latest available financial record for each company.
- Implemented Quality Screener.
- Implemented Low Debt Screener.
- Implemented High ROE Screener.
- Implemented Income Screener.
- Implemented Balanced Screener.
- Generated preset-wise screening reports.
- Created a reusable preset screener module.

## Sprint 3 Progress

The core filter engine and preset screener framework are ready for composite scoring and peer comparison analysis.