# 📅 Day 11 - Cash Flow KPIs & Capital Allocation

## Objectives

- Connect SQLite Database
- Inspect Cash Flow Table
- Calculate Free Cash Flow
- Calculate CFO Quality
- Calculate CapEx Intensity
- Calculate FCF Conversion
- Capital Allocation Pattern
- Export Results

In [1]:
import sqlite3
import pandas as pd
import numpy as np

In [2]:
conn = sqlite3.connect("../database/nifty100.db")

print("Database Connected Successfully")

Database Connected Successfully

In [3]:
tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

tables

            name
0      companies
1       analysis
2   balancesheet
3       cashflow
4  profitandloss
5      documents
6    prosandcons

In [4]:
cashflow = pd.read_sql(
    "PRAGMA table_info(cashflow)",
    conn
)

cashflow

,cid,name,type,notnull,dflt_value,pk
0,0,bluestock_fintech_—_nifty_100__|__cash_flow__|...,TEXT,0,None,0
1,1,unnamed:_1,TEXT,0,None,0
2,2,unnamed:_2,TEXT,0,None,0
3,3,unnamed:_3,TEXT,0,None,0
4,4,unnamed:_4,TEXT,0,None,0
5,5,unnamed:_5,TEXT,0,None,0
6,6,unnamed:_6,TEXT,0,None,0

In [5]:
pl = pd.read_sql(
    "PRAGMA table_info(profitandloss)",
    conn
)

pl

,cid,name,type,notnull,dflt_value,pk
0,0,bluestock_fintech_—_nifty_100__|__profit_&_los...,TEXT,0,None,0
1,1,unnamed:_1,TEXT,0,None,0
2,2,unnamed:_2,TEXT,0,None,0
3,3,unnamed:_3,TEXT,0,None,0
4,4,unnamed:_4,TEXT,0,None,0
5,5,unnamed:_5,TEXT,0,None,0
6,6,unnamed:_6,TEXT,0,None,0
7,7,unnamed:_7,TEXT,0,None,0
8,8,unnamed:_8,TEXT,0,None,0
9,9,unnamed:_9,TEXT,0,None,0
10,10,unnamed:_10,TEXT,0,None,0
11,11,unnamed:_11,TEXT,0,None,0
12,12,unnamed:_12,TEXT,0,None,0
13,13,unnamed:_13,TEXT,0,None,0
14,14,unnamed:_14,TEXT,0,None,0

In [6]:
cashflow_df = pd.read_sql("SELECT * FROM cashflow LIMIT 5", conn)
cashflow_df

,"bluestock_fintech_—_nifty_100__|__cash_flow__|__1,187_records",unnamed:_1,unnamed:_2,unnamed:_3,unnamed:_4,unnamed:_5,unnamed:_6
0,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
1,37,TCS,Mar-13,11615,-6038,-5729,-152
2,38,TCS,Mar-14,14751,-9452,-5673,-374
3,39,TCS,Mar-15,19369,-1807,-17168,394
4,40,TCS,Mar-16,19109,-5010,-9666,4433

In [7]:
pl_df = pd.read_sql("SELECT * FROM profitandloss LIMIT 5", conn)
pl_df

,"bluestock_fintech_—_nifty_100__|__profit_&_loss__|__1,276_records",unnamed:_1,unnamed:_2,unnamed:_3,unnamed:_4,unnamed:_5,unnamed:_6,unnamed:_7,unnamed:_8,unnamed:_9,unnamed:_10,unnamed:_11,unnamed:_12,unnamed:_13,unnamed:_14
0,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
1,61,ABB,Dec 2012,1653,1451,202,12,33,0,19,215,33,145,68,25
2,62,ABB,Mar 2014,2276,2009,267,12,49,0,22,295,33,198,93,25
3,63,ABB,Mar 2015,2289,1977,312,14,48,0,15,344,34,229,108,29
4,64,ABB,Mar 2016,2614,2250,365,14,50,3,14,398,36,255,120,29

In [8]:
cashflow_df = pd.read_sql("SELECT * FROM cashflow LIMIT 5", conn)
cashflow_df

,"bluestock_fintech_—_nifty_100__|__cash_flow__|__1,187_records",unnamed:_1,unnamed:_2,unnamed:_3,unnamed:_4,unnamed:_5,unnamed:_6
0,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
1,37,TCS,Mar-13,11615,-6038,-5729,-152
2,38,TCS,Mar-14,14751,-9452,-5673,-374
3,39,TCS,Mar-15,19369,-1807,-17168,394
4,40,TCS,Mar-16,19109,-5010,-9666,4433

In [9]:
pl_df = pd.read_sql("SELECT * FROM profitandloss LIMIT 5", conn)
pl_df

,"bluestock_fintech_—_nifty_100__|__profit_&_loss__|__1,276_records",unnamed:_1,unnamed:_2,unnamed:_3,unnamed:_4,unnamed:_5,unnamed:_6,unnamed:_7,unnamed:_8,unnamed:_9,unnamed:_10,unnamed:_11,unnamed:_12,unnamed:_13,unnamed:_14
0,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
1,61,ABB,Dec 2012,1653,1451,202,12,33,0,19,215,33,145,68,25
2,62,ABB,Mar 2014,2276,2009,267,12,49,0,22,295,33,198,93,25
3,63,ABB,Mar 2015,2289,1977,312,14,48,0,15,344,34,229,108,29
4,64,ABB,Mar 2016,2614,2250,365,14,50,3,14,398,36,255,120,29

In [10]:
cashflow = pd.read_sql("SELECT * FROM cashflow", conn)

In [11]:
cashflow.columns = cashflow.iloc[0]

In [12]:
cashflow = cashflow.iloc[1:].reset_index(drop=True)

In [13]:
cashflow.head()

,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
0,37,TCS,Mar-13,11615,-6038,-5729,-152
1,38,TCS,Mar-14,14751,-9452,-5673,-374
2,39,TCS,Mar-15,19369,-1807,-17168,394
3,40,TCS,Mar-16,19109,-5010,-9666,4433
4,41,TCS,Mar-17,25223,-16895,-11026,-2698

In [14]:
pl = pd.read_sql("SELECT * FROM profitandloss", conn)

pl.columns = pl.iloc[0]

pl = pl.iloc[1:].reset_index(drop=True)

pl.head()

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
0,61,ABB,Dec 2012,1653,1451,202,12,33,0,19,215,33,145,68,25
1,62,ABB,Mar 2014,2276,2009,267,12,49,0,22,295,33,198,93,25
2,63,ABB,Mar 2015,2289,1977,312,14,48,0,15,344,34,229,108,29
3,64,ABB,Mar 2016,2614,2250,365,14,50,3,14,398,36,255,120,29
4,65,ABB,Mar 2017,2903,2505,398,14,57,2,16,436,37,277,130,31

In [15]:
df = cashflow.merge(
    pl,
    on=["company_id", "year"],
    how="inner"
)

df.head()

,id_x,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow,id_y,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
0,61,ABB,Dec 2012,101,-59,-42,1,61,1653,1451,202,12,33,0,19,215,33,145,68,25
1,62,ABB,Mar 2014,155,-144,-42,-31,62,2276,2009,267,12,49,0,22,295,33,198,93,25
2,63,ABB,Mar 2015,215,-187,-58,-30,63,2289,1977,312,14,48,0,15,344,34,229,108,29
3,64,ABB,Mar 2016,249,-77,-80,91,64,2614,2250,365,14,50,3,14,398,36,255,120,29
4,65,ABB,Mar 2017,307,-155,-90,62,65,2903,2505,398,14,57,2,16,436,37,277,130,31

In [16]:
numeric_cols = [
    "operating_activity",
    "investing_activity",
    "financing_activity",
    "operating_profit",
    "sales",
    "net_profit"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df.dtypes

0
id_x                      str
company_id                str
year                      str
operating_activity    float64
investing_activity    float64
financing_activity    float64
net_cash_flow             str
id_y                      str
sales                   int64
expenses                  str
operating_profit      float64
opm_percentage            str
other_income              str
interest                  str
depreciation              str
profit_before_tax         str
tax_percentage            str
net_profit              int64
eps                       str
dividend_payout           str
dtype: object

In [17]:
df["free_cash_flow"] = (
    df["operating_activity"] +
    df["investing_activity"]
)

df[
    [
        "company_id",
        "year",
        "operating_activity",
        "investing_activity",
        "free_cash_flow"
    ]
].head()

0 company_id      year  operating_activity  investing_activity  free_cash_flow
0        ABB  Dec 2012               101.0               -59.0            42.0
1        ABB  Mar 2014               155.0              -144.0            11.0
2        ABB  Mar 2015               215.0              -187.0            28.0
3        ABB  Mar 2016               249.0               -77.0           172.0
4        ABB  Mar 2017               307.0              -155.0           152.0

In [18]:
import numpy as np

df["fcf_conversion_rate"] = np.where(
    df["operating_profit"] == 0,
    np.nan,
    (df["free_cash_flow"] / df["operating_profit"]) * 100
)

df[
    [
        "company_id",
        "year",
        "free_cash_flow",
        "operating_profit",
        "fcf_conversion_rate"
    ]
].head()

0 company_id      year  free_cash_flow  operating_profit  fcf_conversion_rate
0        ABB  Dec 2012            42.0             202.0            20.792079
1        ABB  Mar 2014            11.0             267.0             4.119850
2        ABB  Mar 2015            28.0             312.0             8.974359
3        ABB  Mar 2016           172.0             365.0            47.123288
4        ABB  Mar 2017           152.0             398.0            38.190955

In [20]:
df["capex_intensity"] = np.where(
    df["sales"] == 0,
    np.nan,
    (abs(df["investing_activity"]) / df["sales"]) * 100
)

df[
    [
        "company_id",
        "year",
        "sales",
        "investing_activity",
        "capex_intensity"
    ]
].head()

0 company_id      year  sales  investing_activity  capex_intensity
0        ABB  Dec 2012   1653               -59.0         3.569268
1        ABB  Mar 2014   2276              -144.0         6.326889
2        ABB  Mar 2015   2289              -187.0         8.169506
3        ABB  Mar 2016   2614               -77.0         2.945677
4        ABB  Mar 2017   2903              -155.0         5.339304

In [21]:
df["cfo_pat_ratio"] = np.where(
    df["net_profit"] == 0,
    np.nan,
    df["operating_activity"] / df["net_profit"]
)

df[
    [
        "company_id",
        "year",
        "operating_activity",
        "net_profit",
        "cfo_pat_ratio"
    ]
].head()

0 company_id      year  operating_activity  net_profit  cfo_pat_ratio
0        ABB  Dec 2012               101.0         145       0.696552
1        ABB  Mar 2014               155.0         198       0.782828
2        ABB  Mar 2015               215.0         229       0.938865
3        ABB  Mar 2016               249.0         255       0.976471
4        ABB  Mar 2017               307.0         277       1.108303

In [22]:
df["cfo_pat_avg_5yr"] = (
    df.groupby("company_id")["cfo_pat_ratio"]
      .transform(lambda x: x.rolling(5, min_periods=1).mean())
)

df[
    [
        "company_id",
        "year",
        "cfo_pat_ratio",
        "cfo_pat_avg_5yr"
    ]
].head(10)

0 company_id      year  cfo_pat_ratio  cfo_pat_avg_5yr
0        ABB  Dec 2012       0.696552         0.696552
1        ABB  Mar 2014       0.782828         0.739690
2        ABB  Mar 2015       0.938865         0.806082
3        ABB  Mar 2016       0.976471         0.848679
4        ABB  Mar 2017       1.108303         0.900604
5        ABB  Mar 2018       0.381546         0.837603
6        ABB  Mar 2019       1.108889         0.902815
7        ABB  Mar 2020       1.055649         0.926172
8        ABB  Mar 2021       1.052098         0.941297
9        ABB  Mar 2022       1.186483         0.956933

In [23]:
def cfo_quality(score):
    if pd.isna(score):
        return None
    elif score > 1:
        return "High Quality"
    elif score >= 0.5:
        return "Moderate"
    else:
        return "Accrual Risk"

df["cfo_quality"] = df["cfo_pat_avg_5yr"].apply(cfo_quality)

df[
    [
        "company_id",
        "year",
        "cfo_pat_avg_5yr",
        "cfo_quality"
    ]
].head(10)

0 company_id      year  cfo_pat_avg_5yr cfo_quality
0        ABB  Dec 2012         0.696552    Moderate
1        ABB  Mar 2014         0.739690    Moderate
2        ABB  Mar 2015         0.806082    Moderate
3        ABB  Mar 2016         0.848679    Moderate
4        ABB  Mar 2017         0.900604    Moderate
5        ABB  Mar 2018         0.837603    Moderate
6        ABB  Mar 2019         0.902815    Moderate
7        ABB  Mar 2020         0.926172    Moderate
8        ABB  Mar 2021         0.941297    Moderate
9        ABB  Mar 2022         0.956933    Moderate

In [24]:
df["cfo_sign"] = np.where(df["operating_activity"] >= 0, "+", "-")
df["cfi_sign"] = np.where(df["investing_activity"] >= 0, "+", "-")
df["cff_sign"] = np.where(df["financing_activity"] >= 0, "+", "-")

df["pattern"] = (
    df["cfo_sign"] +
    df["cfi_sign"] +
    df["cff_sign"]
)

df[
    [
        "company_id",
        "year",
        "operating_activity",
        "investing_activity",
        "financing_activity",
        "pattern"
    ]
].head()

,company_id,year,operating_activity,investing_activity,financing_activity,pattern
0,ABB,Dec 2012,101.0,-59.0,-42.0,+--
1,ABB,Mar 2014,155.0,-144.0,-42.0,+--
2,ABB,Mar 2015,215.0,-187.0,-58.0,+--
3,ABB,Mar 2016,249.0,-77.0,-80.0,+--
4,ABB,Mar 2017,307.0,-155.0,-90.0,+--

In [25]:
pattern_labels = {
    "+--": "Reinvestor",
    "+-+": "Shareholder Returns",
    "++-": "Liquidating Assets",
    "-++": "Distress Signal",
    "--+": "Growth Funded by Debt",
    "+++": "Cash Accumulator",
    "---": "Pre-Revenue",
    "+-+": "Mixed"
}

df["capital_allocation"] = (
    df["pattern"]
      .map(pattern_labels)
      .fillna("Mixed")
)

df[
    [
        "company_id",
        "year",
        "pattern",
        "capital_allocation"
    ]
].head(20)

0  company_id      year pattern     capital_allocation
0         ABB  Dec 2012     +--             Reinvestor
1         ABB  Mar 2014     +--             Reinvestor
2         ABB  Mar 2015     +--             Reinvestor
3         ABB  Mar 2016     +--             Reinvestor
4         ABB  Mar 2017     +--             Reinvestor
5         ABB  Mar 2018     +--             Reinvestor
6         ABB  Mar 2019     +--             Reinvestor
7         ABB  Mar 2020     +--             Reinvestor
8         ABB  Mar 2021     +--             Reinvestor
9         ABB  Mar 2022     +--             Reinvestor
10        ABB  Mar 2023     +--             Reinvestor
11        ABB  Mar 2024     +--             Reinvestor
12        ABB  Mar 2014     +++       Cash Accumulator
13        ABB  Mar 2015     --+  Growth Funded by Debt
14        ABB  Mar 2016     +--             Reinvestor
15        ABB  Mar 2017     +--             Reinvestor
16        ABB  Mar 2018     +-+                  Mixed
17        ABB  Mar 2019     +-+                  Mixed
18        ABB  Mar 2020     +-+                  Mixed
19        ABB  Mar 2021     +--             Reinvestor

In [26]:
df.to_csv(
    "../reports/capital_allocation_day11.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully

In [1]:
import os

print(conn)

NameError: name 'conn' is not defined

In [2]:
import os

print("n100.db :", os.path.getsize("../database/n100.db"))
print("nifty100.db :", os.path.getsize("../database/nifty100.db"))

n100.db : 0
nifty100.db : 495616

In [3]:
conn = sqlite3.connect("../database/nifty100.db")

tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

tables

NameError: name 'sqlite3' is not defined

In [4]:
import sqlite3
import pandas as pd
import numpy as np
import os

In [5]:
conn = sqlite3.connect("../database/nifty100.db")

tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

tables

            name
0      companies
1       analysis
2   balancesheet
3       cashflow
4  profitandloss
5      documents
6    prosandcons