# Day 26 - Valuation Analysis

## Objective
Perform valuation analysis on N100 companies by calculating valuation metrics and classifying companies as Undervalued, Fairly Valued, or Overvalued.

## Outputs
- valuation_summary.xlsx
- valuation_flags.csv

In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [2]:
conn = sqlite3.connect("../database/nifty100.db")

In [3]:
tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

tables

            name
0      companies
1       analysis
2   balancesheet
3       cashflow
4  profitandloss
5      documents
6    prosandcons

In [5]:
tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

tables

            name
0      companies
1       analysis
2   balancesheet
3       cashflow
4  profitandloss
5      documents
6    prosandcons

In [6]:
analysis_cols = pd.read_sql("""
PRAGMA table_info(analysis);
""", conn)

analysis_cols

,cid,name,type,notnull,dflt_value,pk
0,0,bluestock_fintech_—_nifty_100__|__analysis__|_...,TEXT,0,None,0
1,1,unnamed:_1,TEXT,0,None,0
2,2,unnamed:_2,TEXT,0,None,0
3,3,unnamed:_3,TEXT,0,None,0
4,4,unnamed:_4,TEXT,0,None,0
5,5,unnamed:_5,TEXT,0,None,0

In [7]:
companies_cols = pd.read_sql("""
PRAGMA table_info(companies);
""", conn)

companies_cols

,cid,name,type,notnull,dflt_value,pk
0,0,mkt_fintech_—_nifty_100__|__companies__|__92_r...,TEXT,0,None,0
1,1,unnamed:_1,TEXT,0,None,0
2,2,unnamed:_2,TEXT,0,None,0
3,3,unnamed:_3,TEXT,0,None,0
4,4,unnamed:_4,TEXT,0,None,0
5,5,unnamed:_5,TEXT,0,None,0
6,6,unnamed:_6,TEXT,0,None,0
7,7,unnamed:_7,TEXT,0,None,0
8,8,unnamed:_8,TEXT,0,None,0
9,9,unnamed:_9,TEXT,0,None,0
10,10,unnamed:_10,TEXT,0,None,0
11,11,unnamed:_11,TEXT,0,None,0

In [8]:
bs_cols = pd.read_sql("""
PRAGMA table_info(balancesheet);
""", conn)

bs_cols

,cid,name,type,notnull,dflt_value,pk
0,0,bluestock_fintech_—_nifty_100__|__balance_shee...,TEXT,0,None,0
1,1,unnamed:_1,TEXT,0,None,0
2,2,unnamed:_2,TEXT,0,None,0
3,3,unnamed:_3,TEXT,0,None,0
4,4,unnamed:_4,TEXT,0,None,0
5,5,unnamed:_5,TEXT,0,None,0
6,6,unnamed:_6,TEXT,0,None,0
7,7,unnamed:_7,TEXT,0,None,0
8,8,unnamed:_8,TEXT,0,None,0
9,9,unnamed:_9,TEXT,0,None,0
10,10,unnamed:_10,TEXT,0,None,0
11,11,unnamed:_11,TEXT,0,None,0
12,12,unnamed:_12,TEXT,0,None,0

In [9]:
pl_cols = pd.read_sql("""
PRAGMA table_info(profitandloss);
""", conn)

pl_cols

,cid,name,type,notnull,dflt_value,pk
0,0,bluestock_fintech_—_nifty_100__|__profit_&_los...,TEXT,0,None,0
1,1,unnamed:_1,TEXT,0,None,0
2,2,unnamed:_2,TEXT,0,None,0
3,3,unnamed:_3,TEXT,0,None,0
4,4,unnamed:_4,TEXT,0,None,0
5,5,unnamed:_5,TEXT,0,None,0
6,6,unnamed:_6,TEXT,0,None,0
7,7,unnamed:_7,TEXT,0,None,0
8,8,unnamed:_8,TEXT,0,None,0
9,9,unnamed:_9,TEXT,0,None,0
10,10,unnamed:_10,TEXT,0,None,0
11,11,unnamed:_11,TEXT,0,None,0
12,12,unnamed:_12,TEXT,0,None,0
13,13,unnamed:_13,TEXT,0,None,0
14,14,unnamed:_14,TEXT,0,None,0

In [10]:
analysis = pd.read_sql("SELECT * FROM analysis LIMIT 5;", conn)
analysis

,bluestock_fintech_—_nifty_100__|__analysis__|__20_records,unnamed:_1,unnamed:_2,unnamed:_3,unnamed:_4,unnamed:_5
0,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
1,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
2,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
3,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
4,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%

In [11]:
companies = pd.read_sql("SELECT * FROM companies LIMIT 5;", conn)
companies

,mkt_fintech_—_nifty_100__|__companies__|__92_records,unnamed:_1,unnamed:_2,unnamed:_3,unnamed:_4,unnamed:_5,unnamed:_6,unnamed:_7,unnamed:_8,unnamed:_9,unnamed:_10,unnamed:_11
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7

In [12]:
balancesheet = pd.read_sql("SELECT * FROM balancesheet LIMIT 5;", conn)
balancesheet

,"bluestock_fintech_—_nifty_100__|__balance_sheet__|__1,312_records",unnamed:_1,unnamed:_2,unnamed:_3,unnamed:_4,unnamed:_5,unnamed:_6,unnamed:_7,unnamed:_8,unnamed:_9,unnamed:_10,unnamed:_11,unnamed:_12
0,id,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_asset,total_assets
1,136,ABB,Dec 2012,21,626,0,260,907,109,1,0,798,907
2,137,ABB,Mar 2014,21,767,0,351,1139,98,1,0,1040,1139
3,138,ABB,Mar 2015,21,916,0,436,1374,96,4,0,1274,1374
4,139,ABB,Mar 2016,21,1174,0,421,1616,108,3,0,1505,1616

In [13]:
profitandloss = pd.read_sql("SELECT * FROM profitandloss LIMIT 5;", conn)
profitandloss

,"bluestock_fintech_—_nifty_100__|__profit_&_loss__|__1,276_records",unnamed:_1,unnamed:_2,unnamed:_3,unnamed:_4,unnamed:_5,unnamed:_6,unnamed:_7,unnamed:_8,unnamed:_9,unnamed:_10,unnamed:_11,unnamed:_12,unnamed:_13,unnamed:_14
0,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
1,61,ABB,Dec 2012,1653,1451,202,12,33,0,19,215,33,145,68,25
2,62,ABB,Mar 2014,2276,2009,267,12,49,0,22,295,33,198,93,25
3,63,ABB,Mar 2015,2289,1977,312,14,48,0,15,344,34,229,108,29
4,64,ABB,Mar 2016,2614,2250,365,14,50,3,14,398,36,255,120,29

In [14]:
analysis = pd.read_sql("SELECT * FROM analysis", conn)
analysis.columns = analysis.iloc[0]
analysis = analysis.iloc[1:]
analysis.head()

,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
1,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
2,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
3,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
4,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%
5,13,TCS,10 Years: 11%,10 Years: 9%,10 Years: 14%,10 Years: 40%

In [15]:
profit = pd.read_sql("SELECT * FROM profitandloss", conn)
profit.columns = profit.iloc[0]
profit = profit.iloc[1:]
profit.head()

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
1,61,ABB,Dec 2012,1653,1451,202,12,33,0,19,215,33,145,68,25
2,62,ABB,Mar 2014,2276,2009,267,12,49,0,22,295,33,198,93,25
3,63,ABB,Mar 2015,2289,1977,312,14,48,0,15,344,34,229,108,29
4,64,ABB,Mar 2016,2614,2250,365,14,50,3,14,398,36,255,120,29
5,65,ABB,Mar 2017,2903,2505,398,14,57,2,16,436,37,277,130,31

In [16]:
balance = pd.read_sql("SELECT * FROM balancesheet", conn)
balance.columns = balance.iloc[0]
balance = balance.iloc[1:]
balance.head()

,id,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_asset,total_assets
1,136,ABB,Dec 2012,21,626,0,260,907,109,1,0,798,907
2,137,ABB,Mar 2014,21,767,0,351,1139,98,1,0,1040,1139
3,138,ABB,Mar 2015,21,916,0,436,1374,96,4,0,1274,1374
4,139,ABB,Mar 2016,21,1174,0,421,1616,108,3,0,1505,1616
5,140,ABB,Mar 2017,21,1366,0,679,2066,110,6,0,1950,2066

In [17]:
valuation = profit.merge(
    analysis[["company_id", "roe"]],
    on="company_id",
    how="left"
)

valuation.head()

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout,roe
0,61,ABB,Dec 2012,1653,1451,202,12,33,0,19,215,33,145,68,25,NaN
1,62,ABB,Mar 2014,2276,2009,267,12,49,0,22,295,33,198,93,25,NaN
2,63,ABB,Mar 2015,2289,1977,312,14,48,0,15,344,34,229,108,29,NaN
3,64,ABB,Mar 2016,2614,2250,365,14,50,3,14,398,36,255,120,29,NaN
4,65,ABB,Mar 2017,2903,2505,398,14,57,2,16,436,37,277,130,31,NaN

In [18]:
valuation["roe"] = (
    valuation["roe"]
    .astype(str)
    .str.extract(r'(-?\d+\.?\d*)')[0]
    .astype(float)
)

valuation["opm_percentage"] = valuation["opm_percentage"].astype(float)
valuation["net_profit"] = valuation["net_profit"].astype(float)

In [19]:
valuation["valuation_score"] = (
    valuation["roe"] * 0.4 +
    valuation["opm_percentage"] * 0.3 +
    valuation["net_profit"] * 0.3
)

In [20]:
def rating(score):
    if score >= 100:
        return "Strong"
    elif score >= 50:
        return "Moderate"
    else:
        return "Weak"

valuation["valuation_rating"] = valuation["valuation_score"].apply(rating)

In [21]:
final = valuation[
    [
        "company_id",
        "roe",
        "opm_percentage",
        "net_profit",
        "valuation_score",
        "valuation_rating"
    ]
]

final.head()

,company_id,roe,opm_percentage,net_profit,valuation_score,valuation_rating
0,ABB,NaN,12.0,145.0,NaN,Weak
1,ABB,NaN,12.0,198.0,NaN,Weak
2,ABB,NaN,14.0,229.0,NaN,Weak
3,ABB,NaN,14.0,255.0,NaN,Weak
4,ABB,NaN,14.0,277.0,NaN,Weak

In [22]:
final.to_csv("../reports/valuation_flags.csv", index=False)

In [23]:
final.to_excel("../reports/valuation_summary.xlsx", index=False)

In [24]:
print(final.shape)

final.head(10)

(1471, 6)

,company_id,roe,opm_percentage,net_profit,valuation_score,valuation_rating
0,ABB,NaN,12.0,145.0,NaN,Weak
1,ABB,NaN,12.0,198.0,NaN,Weak
2,ABB,NaN,14.0,229.0,NaN,Weak
3,ABB,NaN,14.0,255.0,NaN,Weak
4,ABB,NaN,14.0,277.0,NaN,Weak
5,ABB,NaN,16.0,401.0,NaN,Weak
6,ABB,NaN,16.0,450.0,NaN,Weak
7,ABB,NaN,18.0,593.0,NaN,Weak
8,ABB,NaN,21.0,691.0,NaN,Weak
9,ABB,NaN,22.0,799.0,NaN,Weak