In [1]:
import pandas as pd
import numpy as np

In [2]:
import os

for file in sorted(os.listdir("../reports")):
    print(file)

benchmark_companies.csv
benchmark_companies_day7.csv
capital_allocation_day11.csv
company_ranking_day13.csv
day14_infinite_values_report.csv
day14_missing_values_report.csv
day14_ratio_edge_cases.csv
day14_validation_summary.csv
day15_filter_summary.csv
day15_screener_output.csv
day16_all_preset_results.csv
day16_balanced_screener.csv
day16_high_roe_screener.csv
day16_income_screener.csv
day16_low_debt_screener.csv
day16_preset_summary.csv
day16_quality_screener.csv
day17_composite_scores.csv
day17_score_band_summary.csv
day17_top20_companies.csv
day18_benchmark_peer_performance.csv
day18_peer_comparison.csv
day18_peer_leaders.csv
day18_peer_percentiles.csv
day19_declining_companies.csv
day19_financial_trends.csv
day19_latest_company_trends.csv
day19_top_improving_companies.csv
day19_trend_distribution.csv
day20_company_risk_report.csv
day20_high_risk_companies.csv
day20_low_risk_companies.csv
day20_risk_distribution.csv
day20_risk_driver_distribution.csv
day21_decision_summary.csv
day21_investment_decisions.csv
day21_investment_warning_list.csv
day21_recommendation_distribution.csv
day21_top10_investment_ranking.csv
day21_top_investment_candidates.csv
financial_ratios_day12.csv
highest_price_stocks.csv
peer_group_distribution.csv
sector_distribution.csv
top_market_cap_companies.csv
top_market_cap_day7.csv
top_roce_companies.csv
top_roe_companies.csv
top_volume_stocks.csv

In [3]:
recommendation_path = "../reports/day21_investment_recommendation.csv"

df = pd.read_csv(recommendation_path)

print(df.shape)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../reports/day21_investment_recommendation.csv'

In [4]:
import os

print("DAY 21 FILES")
print("="*50)

for file in sorted(os.listdir("../reports")):
    if "day21" in file.lower():
        print(file)

DAY 21 FILES
==================================================
day21_decision_summary.csv
day21_investment_decisions.csv
day21_investment_warning_list.csv
day21_recommendation_distribution.csv
day21_top10_investment_ranking.csv
day21_top_investment_candidates.csv

In [5]:
candidate_path = "../reports/day21_top_investment_candidates.csv"

df = pd.read_csv(candidate_path)

print(df.shape)
print(df.columns.tolist())

df.head()

(5, 15)
['company_id', 'composite_score', 'financial_momentum_score', 'trend_classification', 'normalized_risk_score', 'risk_category', 'primary_risk_driver', 'quality_score_100', 'momentum_score_100', 'safety_score_100', 'final_investment_score', 'recommendation', 'recommendation_confidence', 'confidence_level', 'investment_rank']

,company_id,composite_score,financial_momentum_score,trend_classification,normalized_risk_score,risk_category,primary_risk_driver,quality_score_100,momentum_score_100,safety_score_100,final_investment_score,recommendation,recommendation_confidence,confidence_level,investment_rank
0,BEL,73.189325,3,Strong Improvement,6.67,Low Risk,Debt Risk,100.00,85.71,93.33,95.14,Strong Buy,90.28,High Confidence,1
1,HAL,58.206714,0,Declining,13.33,Low Risk,Debt Risk,79.45,42.86,86.67,74.30,Buy,48.60,Moderate Confidence,2
2,TRENT,25.274906,4,Strong Improvement,6.67,Low Risk,Asset Efficiency Risk,34.29,100.00,93.33,65.14,Buy,30.28,Moderate Confidence,3
3,INDIGO,37.526171,1,Improving,6.67,Low Risk,Financial Momentum Risk,51.09,57.14,93.33,64.97,Buy,29.94,Low Confidence,4
4,ABB,31.765038,2,Improving,13.33,Low Risk,Asset Efficiency Risk,43.19,71.43,86.67,61.88,Buy,23.76,Low Confidence,5

In [6]:
portfolio = df[
    [
        "company_id",
        "composite_score",
        "quality_score_100",
        "momentum_score_100",
        "normalized_risk_score",
        "risk_category",
        "trend_classification"
    ]
].copy()

portfolio

,company_id,composite_score,quality_score_100,momentum_score_100,normalized_risk_score,risk_category,trend_classification
0,BEL,73.189325,100.00,85.71,6.67,Low Risk,Strong Improvement
1,HAL,58.206714,79.45,42.86,13.33,Low Risk,Declining
2,TRENT,25.274906,34.29,100.00,6.67,Low Risk,Strong Improvement
3,INDIGO,37.526171,51.09,57.14,6.67,Low Risk,Improving
4,ABB,31.765038,43.19,71.43,13.33,Low Risk,Improving

In [7]:
portfolio = portfolio.sort_values(
    by="composite_score",
    ascending=False
).reset_index(drop=True)

portfolio["portfolio_rank"] = portfolio.index + 1

portfolio

,company_id,composite_score,quality_score_100,momentum_score_100,normalized_risk_score,risk_category,trend_classification,portfolio_rank
0,BEL,73.189325,100.00,85.71,6.67,Low Risk,Strong Improvement,1
1,HAL,58.206714,79.45,42.86,13.33,Low Risk,Declining,2
2,INDIGO,37.526171,51.09,57.14,6.67,Low Risk,Improving,3
3,ABB,31.765038,43.19,71.43,13.33,Low Risk,Improving,4
4,TRENT,25.274906,34.29,100.00,6.67,Low Risk,Strong Improvement,5

In [8]:
portfolio["allocation_percent"] = (
    portfolio["composite_score"]
    / portfolio["composite_score"].sum()
) * 100

portfolio["allocation_percent"] = portfolio[
    "allocation_percent"
].round(2)

portfolio

,company_id,composite_score,quality_score_100,momentum_score_100,normalized_risk_score,risk_category,trend_classification,portfolio_rank,allocation_percent
0,BEL,73.189325,100.00,85.71,6.67,Low Risk,Strong Improvement,1,32.39
1,HAL,58.206714,79.45,42.86,13.33,Low Risk,Declining,2,25.76
2,INDIGO,37.526171,51.09,57.14,6.67,Low Risk,Improving,3,16.61
3,ABB,31.765038,43.19,71.43,13.33,Low Risk,Improving,4,14.06
4,TRENT,25.274906,34.29,100.00,6.67,Low Risk,Strong Improvement,5,11.19

In [9]:
def recommendation(score):
    if score >= 70:
        return "Strong Buy"
    elif score >= 50:
        return "Buy"
    elif score >= 30:
        return "Hold"
    else:
        return "Watch"

portfolio["recommendation"] = portfolio[
    "composite_score"
].apply(recommendation)

portfolio

,company_id,composite_score,quality_score_100,momentum_score_100,normalized_risk_score,risk_category,trend_classification,portfolio_rank,allocation_percent,recommendation
0,BEL,73.189325,100.00,85.71,6.67,Low Risk,Strong Improvement,1,32.39,Strong Buy
1,HAL,58.206714,79.45,42.86,13.33,Low Risk,Declining,2,25.76,Buy
2,INDIGO,37.526171,51.09,57.14,6.67,Low Risk,Improving,3,16.61,Hold
3,ABB,31.765038,43.19,71.43,13.33,Low Risk,Improving,4,14.06,Hold
4,TRENT,25.274906,34.29,100.00,6.67,Low Risk,Strong Improvement,5,11.19,Watch

In [10]:
portfolio = portfolio[
    [
        "portfolio_rank",
        "company_id",
        "recommendation",
        "allocation_percent",
        "composite_score",
        "quality_score_100",
        "momentum_score_100",
        "normalized_risk_score",
        "risk_category",
        "trend_classification"
    ]
]

portfolio

,portfolio_rank,company_id,recommendation,allocation_percent,composite_score,quality_score_100,momentum_score_100,normalized_risk_score,risk_category,trend_classification
0,1,BEL,Strong Buy,32.39,73.189325,100.00,85.71,6.67,Low Risk,Strong Improvement
1,2,HAL,Buy,25.76,58.206714,79.45,42.86,13.33,Low Risk,Declining
2,3,INDIGO,Hold,16.61,37.526171,51.09,57.14,6.67,Low Risk,Improving
3,4,ABB,Hold,14.06,31.765038,43.19,71.43,13.33,Low Risk,Improving
4,5,TRENT,Watch,11.19,25.274906,34.29,100.00,6.67,Low Risk,Strong Improvement

In [11]:
portfolio.to_csv(
    "../reports/day22_portfolio.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully

In [12]:
print("="*50)
print("PORTFOLIO SUMMARY")
print("="*50)

print("Companies :", len(portfolio))
print("Average Score :", round(portfolio["composite_score"].mean(),2))
print("Average Allocation :", round(portfolio["allocation_percent"].mean(),2))

portfolio

==================================================
PORTFOLIO SUMMARY
==================================================
Companies : 5
Average Score : 45.19
Average Allocation : 20.0

,portfolio_rank,company_id,recommendation,allocation_percent,composite_score,quality_score_100,momentum_score_100,normalized_risk_score,risk_category,trend_classification
0,1,BEL,Strong Buy,32.39,73.189325,100.00,85.71,6.67,Low Risk,Strong Improvement
1,2,HAL,Buy,25.76,58.206714,79.45,42.86,13.33,Low Risk,Declining
2,3,INDIGO,Hold,16.61,37.526171,51.09,57.14,6.67,Low Risk,Improving
3,4,ABB,Hold,14.06,31.765038,43.19,71.43,13.33,Low Risk,Improving
4,5,TRENT,Watch,11.19,25.274906,34.29,100.00,6.67,Low Risk,Strong Improvement