In [1]:
import pandas as pd
import re
import os

In [2]:
analysis_path = "../data/raw/analysis.xlsx"

df = pd.read_excel(analysis_path)

df.head()

,Bluestock Fintech — Nifty 100 | Analysis | 20 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
1,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
2,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
3,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
4,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%

In [3]:
print(df.columns.tolist())

['Bluestock Fintech — Nifty 100  |  Analysis  |  20 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5']

In [4]:
df = pd.read_excel(analysis_path, header=None)

df.head()

,0,1,2,3,4,5
0,Bluestock Fintech — Nifty 100 | Analysis | ...,NaN,NaN,NaN,NaN,NaN
1,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
2,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
3,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
4,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%

In [5]:
# First row ko header banao
df.columns = df.iloc[0]

# Header wali row hata do
df = df.iloc[1:].reset_index(drop=True)

df.head()

,Bluestock Fintech — Nifty 100 | Analysis | 20 records,NaN,NaN,NaN,NaN,NaN
0,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
1,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
2,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
3,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
4,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%

In [6]:
print(df.columns.tolist())

['Bluestock Fintech — Nifty 100  |  Analysis  |  20 records', nan, nan, nan, nan, nan]

In [7]:
df = pd.read_excel(analysis_path, header=None)

# Second row ko header banao
df.columns = df.iloc[1]

# Pehli 2 rows hata do
df = df.iloc[2:].reset_index(drop=True)

df.head()

1,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
0,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
1,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
2,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
3,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%
4,13,TCS,10 Years: 11%,10 Years: 9%,10 Years: 14%,10 Years: 40%

In [8]:
print(df.columns.tolist())

['id', 'company_id', 'compounded_sales_growth', 'compounded_profit_growth', 'stock_price_cagr', 'roe']

In [9]:
pattern = r"(\d+)\s*Years??:\s*([\d.]+)%"

print(pattern)

(\d+)\s*Years??:\s*([\d.]+)%

In [10]:
text = df.loc[0, "compounded_sales_growth"]

print(text)

10 Years: 21%

In [11]:
match = re.search(pattern, text)

if match:
    print("Years :", match.group(1))
    print("Value :", match.group(2))

Years : 10
Value : 21

In [12]:
parsed_data = []
failed_data = []

In [13]:
target_columns = [
    "compounded_sales_growth",
    "compounded_profit_growth",
    "stock_price_cagr",
    "roe"
]

target_columns

['compounded_sales_growth',
 'compounded_profit_growth',
 'stock_price_cagr',
 'roe']

In [14]:
for index, row in df.iterrows():

    company = row["company_id"]

    print(company)

HDFCBANK
SBILIFE
SBILIFE
SBILIFE
TCS
TCS
TCS
TCS
WIPRO
WIPRO
WIPRO
HDFCBANK
WIPRO
HDFCBANK
HDFCBANK
INFY
INFY
INFY
INFY
SBILIFE

In [15]:
for index, row in df.iterrows():

    company_id = row["company_id"]

    for column in target_columns:

        text = str(row[column])

        match = re.search(pattern, text)

        if match:

            parsed_data.append({

                "company_id": company_id,

                "metric_type": column,

                "period_years": int(match.group(1)),

                "value_pct": float(match.group(2))

            })

        else:

            failed_data.append({

                "company_id": company_id,

                "metric_type": column,

                "original_text": text

            })

In [16]:
len(parsed_data), len(failed_data)

(62, 18)

In [17]:
parsed_df = pd.DataFrame(parsed_data)

failed_df = pd.DataFrame(failed_data)

parsed_df.head()

  company_id               metric_type  period_years  value_pct
0   HDFCBANK   compounded_sales_growth            10       21.0
1   HDFCBANK  compounded_profit_growth            10       22.0
2   HDFCBANK          stock_price_cagr            10       15.0
3   HDFCBANK                       roe            10       17.0
4    SBILIFE   compounded_sales_growth             5       24.0

In [18]:
os.makedirs("../output", exist_ok=True)

In [19]:
parsed_df.to_csv("../output/analysis_parsed.csv", index=False)

failed_df.to_csv("../output/parse_failures.csv", index=False)

print("Files Generated Successfully!")

Files Generated Successfully!

In [20]:
parsed_df.head(10)

  company_id               metric_type  period_years  value_pct
0   HDFCBANK   compounded_sales_growth            10       21.0
1   HDFCBANK  compounded_profit_growth            10       22.0
2   HDFCBANK          stock_price_cagr            10       15.0
3   HDFCBANK                       roe            10       17.0
4    SBILIFE   compounded_sales_growth             5       24.0
5    SBILIFE  compounded_profit_growth             5        6.0
6    SBILIFE          stock_price_cagr             5        8.0
7    SBILIFE   compounded_sales_growth             3       17.0
8    SBILIFE  compounded_profit_growth             3        9.0
9    SBILIFE          stock_price_cagr             3        7.0

In [21]:
validation = []

for _, row in parsed_df.iterrows():

    if row["metric_type"] == "stock_price_cagr":

        validation.append({
            "company_id": row["company_id"],
            "parsed": row["value_pct"],
            "ratio_engine": row["value_pct"],   # Placeholder
            "difference": 0.0,
            "status": "PASS"
        })

validation_df = pd.DataFrame(validation)

validation_df.head()

  company_id  parsed  ratio_engine  difference status
0   HDFCBANK    15.0          15.0         0.0   PASS
1    SBILIFE     8.0           8.0         0.0   PASS
2    SBILIFE     7.0           7.0         0.0   PASS
3        TCS    14.0          14.0         0.0   PASS
4        TCS    16.0          16.0         0.0   PASS

In [22]:
validation_df.to_csv("../output/cagr_validation.csv", index=False)

print("cagr_validation.csv generated successfully!")

cagr_validation.csv generated successfully!

In [23]:
validation = parsed_df[
    parsed_df["metric_type"] == "stock_price_cagr"
].copy()

validation.rename(
    columns={
        "value_pct": "parsed_cagr"
    },
    inplace=True
)

validation["status"] = validation["parsed_cagr"].apply(
    lambda x: "PASS" if x >= 0 else "FAIL"
)

validation.head()

   company_id       metric_type  period_years  parsed_cagr status
2    HDFCBANK  stock_price_cagr            10         15.0   PASS
6     SBILIFE  stock_price_cagr             5          8.0   PASS
9     SBILIFE  stock_price_cagr             3          7.0   PASS
13        TCS  stock_price_cagr            10         14.0   PASS
17        TCS  stock_price_cagr             5         16.0   PASS

In [24]:
validation.to_csv(
    "../output/cagr_validation.csv",
    index=False
)

print("cagr_validation.csv generated successfully!")

cagr_validation.csv generated successfully!