In [1]:
import pandas as pd
import os
from datetime import datetime

In [2]:
files = [
    "../output/analysis_parsed.csv",
    "../output/parse_failures.csv",
    "../output/cagr_validation.csv",
    "../output/financial_metrics_standardized.csv",
    "../output/category_summary.csv",
    "../output/company_summary.csv",
    "../output/dashboard_kpis.csv",
    "../output/category_insights.csv",
    "../output/company_insights.csv",
    "../output/dashboard_company_dataset.csv",
    "../output/dashboard_category_dataset.csv",
    "../output/dashboard_summary.csv",
    "../reports/dashboard_testing_report.csv"
]

status = []

for file in files:
    status.append({
        "File": file,
        "Exists": os.path.exists(file)
    })

review_df = pd.DataFrame(status)

review_df

                                            File  Exists
0                  ../output/analysis_parsed.csv    True
1                   ../output/parse_failures.csv    True
2                  ../output/cagr_validation.csv    True
3   ../output/financial_metrics_standardized.csv    True
4                 ../output/category_summary.csv    True
5                  ../output/company_summary.csv    True
6                   ../output/dashboard_kpis.csv    True
7                ../output/category_insights.csv    True
8                 ../output/company_insights.csv    True
9        ../output/dashboard_company_dataset.csv    True
10      ../output/dashboard_category_dataset.csv    True
11               ../output/dashboard_summary.csv    True
12       ../reports/dashboard_testing_report.csv    True

In [3]:
completed = review_df["Exists"].sum()
total = len(review_df)

completion = round((completed / total) * 100, 2)

print("Completion:", completion, "%")

Completion: 100.0 %

In [4]:
summary = pd.DataFrame({
    "Project": ["N100 Financial Intelligence Platform"],
    "Sprint": ["Sprint 5"],
    "Completion (%)": [completion],
    "Status": [
        "Completed" if completion == 100 else "In Progress"
    ],
    "Generated_On": [
        datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ]
})

summary

,Project,Sprint,Completion (%),Status,Generated_On
0,N100 Financial Intelligence Platform,Sprint 5,100.0,Completed,2026-07-24 21:57:13

In [5]:
os.makedirs("../reports", exist_ok=True)

review_df.to_csv(
    "../reports/final_review_report.csv",
    index=False
)

summary.to_csv(
    "../reports/sprint5_completion_report.csv",
    index=False
)

print("Final review reports generated successfully!")

Final review reports generated successfully!

In [6]:
print(review_df)
print()
print(summary)

                                            File  Exists
0                  ../output/analysis_parsed.csv    True
1                   ../output/parse_failures.csv    True
2                  ../output/cagr_validation.csv    True
3   ../output/financial_metrics_standardized.csv    True
4                 ../output/category_summary.csv    True
5                  ../output/company_summary.csv    True
6                   ../output/dashboard_kpis.csv    True
7                ../output/category_insights.csv    True
8                 ../output/company_insights.csv    True
9        ../output/dashboard_company_dataset.csv    True
10      ../output/dashboard_category_dataset.csv    True
11               ../output/dashboard_summary.csv    True
12       ../reports/dashboard_testing_report.csv    True

                                Project    Sprint  Completion (%)     Status  \
0  N100 Financial Intelligence Platform  Sprint 5           100.0  Completed

          Generated_On
0  2026-07-24 21:57:13