In [1]:
import pandas as pd
import os

In [2]:
category = pd.read_csv("../output/category_summary.csv")
company = pd.read_csv("../output/company_summary.csv")

category.head()
company.head()

  company_id  metrics_available  average_score
0   HDFCBANK                 13      18.384615
1       INFY                 13      16.538462
2    SBILIFE                 11      12.818182
3        TCS                 13      19.153846
4      WIPRO                 12      13.333333

In [3]:
kpis = {
    "Total Companies": company["company_id"].nunique(),
    "Total Metrics": company["metrics_available"].sum(),
    "Average Financial Score": round(company["average_score"].mean(), 2),
    "Highest Financial Score": round(company["average_score"].max(), 2),
    "Lowest Financial Score": round(company["average_score"].min(), 2)
}

kpi_df = pd.DataFrame(
    kpis.items(),
    columns=["KPI", "Value"]
)

kpi_df

                       KPI  Value
0          Total Companies   5.00
1            Total Metrics  62.00
2  Average Financial Score  16.05
3  Highest Financial Score  19.15
4   Lowest Financial Score  12.82

In [4]:
category["Insight"] = category["avg_value"].apply(
    lambda x: "Strong" if x >= 20
    else "Moderate" if x >= 10
    else "Weak"
)

category

  metric_category  total_metrics  avg_value  max_value  min_value   Insight
0          Growth             30       13.1       30.0        0.0  Moderate
1   Profitability             14       25.0       47.0       13.0    Strong
2         Returns             18       14.5       39.0        4.0  Moderate

In [5]:
company["Performance"] = company["average_score"].apply(
    lambda x: "Excellent" if x >= 20
    else "Good" if x >= 10
    else "Needs Improvement"
)

company.head()

  company_id  metrics_available  average_score Performance
0   HDFCBANK                 13      18.384615        Good
1       INFY                 13      16.538462        Good
2    SBILIFE                 11      12.818182        Good
3        TCS                 13      19.153846        Good
4      WIPRO                 12      13.333333        Good

In [6]:
os.makedirs("../output", exist_ok=True)

kpi_df.to_csv("../output/dashboard_kpis.csv", index=False)

category.to_csv("../output/category_insights.csv", index=False)

company.to_csv("../output/company_insights.csv", index=False)

print("Day 32 outputs generated successfully!")

Day 32 outputs generated successfully!