In [1]:
print("Day 44 Started")

Day 44 Started

In [2]:
import pandas as pd

portfolio = pd.DataFrame({

"Company":["TCS","INFY","HDFC"],

"Investment":[100000,120000,80000],

"Current Value":[120000,135000,90000]

})

portfolio

  Company  Investment  Current Value
0     TCS      100000         120000
1    INFY      120000         135000
2    HDFC       80000          90000

In [3]:
import pandas as pd

portfolio = pd.DataFrame({

"Company":["TCS","INFY","HDFC"],

"Investment":[100000,120000,80000],

"Current Value":[120000,135000,90000]

})

portfolio

  Company  Investment  Current Value
0     TCS      100000         120000
1    INFY      120000         135000
2    HDFC       80000          90000

In [4]:
portfolio["Profit"]=portfolio["Current Value"]-portfolio["Investment"]

portfolio

  Company  Investment  Current Value  Profit
0     TCS      100000         120000   20000
1    INFY      120000         135000   15000
2    HDFC       80000          90000   10000

In [5]:
portfolio["Return %"]=(

portfolio["Profit"]

/

portfolio["Investment"]

)*100

portfolio

  Company  Investment  Current Value  Profit  Return %
0     TCS      100000         120000   20000      20.0
1    INFY      120000         135000   15000      12.5
2    HDFC       80000          90000   10000      12.5