In [2]:
print("Day 45 Started")

Day 45 Started

In [3]:
import pandas as pd

portfolio = pd.DataFrame({

"Company":["TCS","INFY","HDFC"],

"Investment":[100000,90000,80000],

"Current Value":[125000,93000,78000]

})

portfolio

  Company  Investment  Current Value
0     TCS      100000         125000
1    INFY       90000          93000
2    HDFC       80000          78000

In [4]:
portfolio["Profit"] = portfolio["Current Value"] - portfolio["Investment"]

portfolio["Return %"] = (

portfolio["Profit"]

/

portfolio["Investment"]

)*100

portfolio

  Company  Investment  Current Value  Profit   Return %
0     TCS      100000         125000   25000  25.000000
1    INFY       90000          93000    3000   3.333333
2    HDFC       80000          78000   -2000  -2.500000

In [5]:
portfolio["Recommendation"] = portfolio["Return %"].apply(

lambda x:

"BUY"

if x>20

else

"HOLD"

if x>5

else

"SELL"

)

portfolio

  Company  Investment  Current Value  Profit   Return % Recommendation
0     TCS      100000         125000   25000  25.000000            BUY
1    INFY       90000          93000    3000   3.333333           SELL
2    HDFC       80000          78000   -2000  -2.500000           SELL

In [6]:
print("DAY 45 COMPLETED")

DAY 45 COMPLETED